---
version: 2
updates:
  - package-ecosystem: terraform
    directory: "/"
    schedule:
      interval: daily
      time: "01:00"
    target-branch: main

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
      time: "01:00"
    target-branch: main

